[{"id": "a1be7e52-0dba-4018-83ce-a1598ca68807", "scope": "tests/failing_test.py", "name": "test_failed", "location": "tests/failing_test.py:0", "file_name": "tests/failing_test.py", "history": {"section": "top", "children": [], "start_at": 2e-05, "end_at": 0.012478, "duration": 0.012458}, "result": "failed", "failure_reason": "def test_failed():\n>       assert 3 == 5\nE       assert 3 == 5\n\ntests/failing_test.py:2: AssertionError"}]